services:
  app:
    build: ./
    volumes:
      - .:/workdir
      - ./laravel_app/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    working_dir: /workdir/laravel_app
    ports:
      - 8000:8000
  db:
    image: mysql:8.3
    volumes:
      - ./laravel_app/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306
